### ISSUE TITLE
Just a concern about running this script on Ubuntu 19.10

### ISSUE THREAD

**Issue by vaskark** [ls4154/termite-ubuntu#1]
Hi. I just found your script and am interested in using it as I've wanted to have termite on my Ubuntu system for quite some time. My concern is how it exists along side other installed terminals. Does it interfere with their functioning? I had a problem with a previous termite build script for Ubuntu, and gnome-terminal stopped working. Had to spend quite a bit of time trying to reverse that whole situation.

Just wondering :)

**Comment by ls4154** [comment]
Hi.
Since installing vte-ng breaks the gnome-terminal, I made this script to link vte-ng to termite statically. So It will not make interference to existing terminals. :)

**Comment by vaskark** [comment]
Thanks for responding. I should have read your readme with closer eyes (or at least less tired). So I apologize for the useless post.
I've run your script and everything works great on 19.10.
However, I noticed `ctrl+shift+t` doesn't open a new termite window. And that `termite-static/etc/profile.d/vte.sh` isn't being copied to `/usr/local/etc/profile.d/` so that it can be sourced in `.zshrc`. I suppose it's fine to just copy or link it there myself.
Once again, great work.

**Comment by ls4154** [comment]
I usually source `/etc/profile.d/vte.sh` in my `.bashrc` according to [termite manual](https://github.com/thestinger/termite#insert-mode) or [Arch Wiki](https://wiki.archlinux.org/index.php/Termite#Troubleshooting), but maybe I should make script to copy it in case who don't have vte library installed.
Thanks for the let me know this.
