### ISSUE TITLE
Uninstall mode

### ISSUE THREAD

**Issue by hypernova7** [ls4154/termite-ubuntu#2]
How do I uninstall it completely?

**Comment by ls4154** [comment]
Hi, I just added the uninstall script. Try it out and let me know if you have any problems.

**Comment by hypernova7** [comment]
@ls4154 Thank you very much, it works fine. Sorry for the inconvenience, what happens that termite and vte-ng are causing me a conflict with gnome-terminal when using Ubuntu's default desktop

**Comment by ls4154** [comment]
Does that mean that gnome-terminal doesn't work when you install termite with this script?

**Comment by hypernova7** [comment]
@ls4154 No, it does not work.  And it gives me this error that I still don't know how to solve it.

> /usr/libexec/gnome-terminal-server: symbol lookup error: /usr/libexec/gnome-terminal-server: undefined symbol: vte_text_blink_mode_get_type

**Comment by ls4154** [comment]
Well that's strange. This error message should happens when vte-ng is installed, while my script does not install vte-ng to prevent such error. 

It seems that you have installed vte-ng to your system. If so, you need to uninstall vte-ng to make gnome-terminal work.

**Comment by hypernova7** [comment]
@ls4154 I understand, I have only used your script, I have not done it in any other way than using your script

**Comment by hypernova7** [comment]
I already fixed it, I found out that if I use another script ([this](https://github.com/Corwind/termite-install)).  Sorry for the inconvenience, now I will test if it continues to conflict with your script

**Comment by hypernova7** [comment]
It works perfectly and does not conflict with gnome-terminal.  Really thank you very much for your help and precious time

**Comment by ls4154** [comment]
Glad to hear that it works for you :) Thank you for your feedback!
